# Generated by Django 5.2.3 on 2025-06-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
