# Generated by Django 5.2 on 2025-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
